title: Zalando Open Source
description: Scaling Open Culture
email: opensource@zalando.de

# Do not use the leading @ here
twitter: ZalandoTech

url: "https://opensource.zalando.com"
baseurl: "/"

markdown: kramdown
destination: '_site'
paginate: 5
permalink: /:year/:month/:title/
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-paginate

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'

include:
  - '_pages'
